name: CI

on:
  push:
    branches: 
      - main

jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
      fail-fast: false
    
    defaults:
      run:
        working-directory: ./api
  
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node | ${{matrix.node}}
      uses: actions/setup-node@v4
      with: 
        node-version: ${{matrix.node}}
        cache: 'yarn'
        cache-dependency-path: './api/yarn.lock'
    - run: yarn
    - run: yarn run test

    - name: Generate tag
      id: generate_tag
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: ./api
        push:  true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/api-template-nest:${{steps.generate_tag.outputs.sha}},${{secrets.DOCKERHUB_USERNAME}}/api-template-nest:latest



    # - name: Build docker image
    #   run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/api-template-nest:${{steps.generate_tag.outputs.sha}} .
    # - name: Push image
    #   run: docker push ${{secrets.DOCKERHUB_USERNAME}}/api-template-nest:${{steps.generate_tag.outputs.sha}}
  