name: CI

on:
  push:
    branches: 
      - main


jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with: 
        node-version: 18
        cache: 'yarn'
        cache-dependency-path: api/yarn.lock
    - run: yarn
    - run: yarn run test

